cp -Rf ../zoo45xu/check_time_from_db.py ./
cp -Rf ../zoo45xu/mount.py ./
cp -Rf ../zoo45xu/mount_unmount.py ./
cp -Rf ../zoo45xu/gmail_narita.py ./
cp -Rf ../zoo45xu/Sequence.py ./
cp -Rf ../zoo45xu/pe_test.py ./
cp -Rf ../zoo45xu/INOCC_v2.py ./
cp -Rf ../zoo45xu/LargePlateMatching.py ./
cp -Rf ../zoo45xu/contour13.py ./
cp -Rf ../zoo45xu/log_maker.py ./
cp -Rf ../zoo45xu/ZOOGUI/gui06.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.26.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.24.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_testver.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/test2.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_test_nm.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.2.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.21.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.25.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/read_db_all.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver0.01.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/test.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/gui08.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/gui09.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_NMver3.21.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/gui07.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.1.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver3.25_nm.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_NMver3.24.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_tmp.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/htmlview.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ZOOGUI.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver1.0.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ensoku_ver0.0.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/KamoView.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/ZOOTIMER.py ./ZOOGUI/
cp -Rf ../zoo45xu/ZOOGUI/WebCam.py ./ZOOGUI/
cp -Rf ../zoo45xu/lets_zoo.py ./
cp -Rf ../zoo45xu/get_current_pin.py ./
cp -Rf ../zoo45xu/getBackCam2.py ./
cp -Rf ../zoo45xu/suno3.py ./
cp -Rf ../zoo45xu/28_read_db.py ./
cp -Rf ../zoo45xu/25_feature_detection.py ./
cp -Rf ../zoo45xu/zoozoo.py ./
cp -Rf ../zoo45xu/test_sch.py ./
cp -Rf ../zoo45xu/large_camera_capture.py ./
cp -Rf ../zoo45xu/clean_space.py ./
cp -Rf ../zoo45xu/coa.py ./
cp -Rf ../zoo45xu/DiffscanMaster.py ./
cp -Rf ../zoo45xu/gmail_zoo_report_ver1.0.py ./
cp -Rf ../zoo45xu/16_dose_estimation.py ./
cp -Rf ../zoo45xu/getBackCam1.py ./
cp -Rf ../zoo45xu/24_shape_recognition.py ./
cp -Rf ../zoo45xu/KUMA.py ./
cp -Rf ../zoo45xu/test-zoo.py ./
cp -Rf ../zoo45xu/SummarySHIKA.py ./
cp -Rf ../zoo45xu/lm_check.py ./
cp -Rf ../zoo45xu/test2.py ./
cp -Rf ../zoo45xu/hebi_test.py ./
cp -Rf ../zoo45xu/html_log_maker.py ./
cp -Rf ../zoo45xu/shy_helical.py ./
cp -Rf ../zoo45xu/cap.py ./
cp -Rf ../zoo45xu/LoopMeasurement_v2.py ./
cp -Rf ../zoo45xu/Zoo.py ./
cp -Rf ../zoo45xu/FittingForFacing.py ./
cp -Rf ../zoo45xu/12_rotate_and_capture.py ./
cp -Rf ../zoo45xu/exchange.py ./
cp -Rf ../zoo45xu/LargePlateMatchingCam2.py ./
cp -Rf ../zoo45xu/rastar_scan_time.py ./
cp -Rf ../zoo45xu/26_get_wavelength.py ./
cp -Rf ../zoo45xu/scanMade.py ./
cp -Rf ../zoo45xu/hito_new_test00.py ./
cp -Rf ../zoo45xu/01_capture_pin_series.py ./
cp -Rf ../zoo45xu/mount_check.py ./
cp -Rf ../zoo45xu/cent_test.py ./
cp -Rf ../zoo45xu/make_test_csv.py ./
cp -Rf ../zoo45xu/t2.py ./
cp -Rf ../zoo45xu/set_wavelength.py ./
cp -Rf ../zoo45xu/ZooConditions.py ./
cp -Rf ../zoo45xu/test_centering.py ./
cp -Rf ../zoo45xu/time_test.py ./
cp -Rf ../zoo45xu/20_set_beamsize.py ./
cp -Rf ../zoo45xu/Condition.obsoleted.py ./
cp -Rf ../zoo45xu/auto.py ./
cp -Rf ../zoo45xu/centering.py ./
cp -Rf ../zoo45xu/mod_for_blend.py ./
cp -Rf ../zoo45xu/toyoda_3rd.py ./
cp -Rf ../zoo45xu/RasterSchedule_v2.py ./
cp -Rf ../zoo45xu/29_helical_debug.py ./
cp -Rf ../zoo45xu/do_raster.py ./
cp -Rf ../zoo45xu/testing_my.py ./
cp -Rf ../zoo45xu/mail_report_ver0.00.py ./
cp -Rf ../zoo45xu/c.py ./
cp -Rf ../zoo45xu/brian.py ./
cp -Rf ../zoo45xu/10_check_flux_from_config.py ./
cp -Rf ../zoo45xu/back_cam_cap.py ./
cp -Rf ../zoo45xu/do_collection.py ./
cp -Rf ../zoo45xu/optparse_test.py ./
cp -Rf ../zoo45xu/IboINOCC.py ./
cp -Rf ../zoo45xu/LoopMeasurement.py ./
cp -Rf ../zoo45xu/html.py ./
cp -Rf ../zoo45xu/03_mount_and_centering.py ./
cp -Rf ../zoo45xu/15_facing_test.py ./
cp -Rf ../zoo45xu/ZooNavigator_v2.py ./
cp -Rf ../zoo45xu/04_long_capture.py ./
cp -Rf ../zoo45xu/tune_pint_test.py ./
cp -Rf ../zoo45xu/01_test.py ./
cp -Rf ../zoo45xu/cent.py ./
cp -Rf ../zoo45xu/large_camc.py ./
cp -Rf ../zoo45xu/08_simulate_helical.py ./
cp -Rf ../zoo45xu/hebi_for_debug.py ./
cp -Rf ../zoo45xu/html_maker_test.py ./
cp -Rf ../zoo45xu/Condition.py ./
cp -Rf ../zoo45xu/arg.py ./
cp -Rf ../zoo45xu/INOCC.py ./
cp -Rf ../zoo45xu/server.py ./
cp -Rf ../zoo45xu/HITO.py ./
cp -Rf ../zoo45xu/scanMade0.py ./
cp -Rf ../zoo45xu/gmail_zoo_report_ver1.1.py ./
cp -Rf ../zoo45xu/ZooNavigator.py ./
cp -Rf ../zoo45xu/AV_160926.py ./
cp -Rf ../zoo45xu/mulheli_multi.py ./
cp -Rf ../zoo45xu/auto_select_remerge.py ./
cp -Rf ../zoo45xu/07_html_mouse_over.py ./
cp -Rf ../zoo45xu/ZOO_latest.py ./
cp -Rf ../zoo45xu/read_db_and_report.py ./
cp -Rf ../zoo45xu/raster_scan.py ./
cp -Rf ../zoo45xu/prep_centering.py ./
cp -Rf ../zoo45xu/gmail_zoo_report.py ./
cp -Rf ../zoo45xu/lys.py ./
cp -Rf ../zoo45xu/server_cam2.py ./
cp -Rf ../zoo45xu/hito_new_test01.py ./
cp -Rf ../zoo45xu/Libs/BeamsizeConfig_41.py ./Libs/
cp -Rf ../zoo45xu/Libs/ExSlit1.py ./Libs/
cp -Rf ../zoo45xu/Libs/tcs_zero_h.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZOODB.py ./Libs/
cp -Rf ../zoo45xu/Libs/DumpRecover.py ./Libs/
cp -Rf ../zoo45xu/Libs/BSSconfig.py ./Libs/
cp -Rf ../zoo45xu/Libs/ScheduleBSS_v2.py ./Libs/
cp -Rf ../zoo45xu/Libs/BeamCenter.py ./Libs/
cp -Rf ../zoo45xu/Libs/AxesInfo.py ./Libs/
cp -Rf ../zoo45xu/Libs/File.py ./Libs/
cp -Rf ../zoo45xu/Libs/ID.py ./Libs/
cp -Rf ../zoo45xu/Libs/UserESA_20210329.py ./Libs/
cp -Rf ../zoo45xu/Libs/tcs_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/DBinfo.py ./Libs/
cp -Rf ../zoo45xu/Libs/image.py ./Libs/
cp -Rf ../zoo45xu/Libs/Count.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_attraster.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db_loopsize.py ./Libs/
cp -Rf ../zoo45xu/Libs/open_shutter.py ./Libs/
cp -Rf ../zoo45xu/Libs/CheckESA.py ./Libs/
cp -Rf ../zoo45xu/Libs/PixelCrystal.py ./Libs/
cp -Rf ../zoo45xu/Libs/check_csv.py ./Libs/
cp -Rf ../zoo45xu/Libs/AttFactor.py ./Libs/
cp -Rf ../zoo45xu/Libs/UserESA_202106_nm.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db2.py ./Libs/
cp -Rf ../zoo45xu/Libs/db_html_for_rd.py ./Libs/
cp -Rf ../zoo45xu/Libs/db_report_time.py ./Libs/
cp -Rf ../zoo45xu/Libs/DiffscanLog.py ./Libs/
cp -Rf ../zoo45xu/Libs/BM.py ./Libs/
cp -Rf ../zoo45xu/Libs/CrystalList.py ./Libs/
cp -Rf ../zoo45xu/Libs/Morning.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db_score.py ./Libs/
cp -Rf ../zoo45xu/Libs/colli_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/Shutter.py ./Libs/
cp -Rf ../zoo45xu/Libs/ESA_v2.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_db_all.py ./Libs/
cp -Rf ../zoo45xu/Libs/FES.py ./Libs/
cp -Rf ../zoo45xu/Libs/ConfigFile.py ./Libs/
cp -Rf ../zoo45xu/Libs/Colli.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZOOhtmlMaker_191015.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/analyze_loop.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/00_scan_pixresol_INOCC.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/03_center_test.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/01_scan_pixresol_INOCC.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/00_analyze_loop.py ./Libs/
cp -Rf ../zoo45xu/Libs/TuneCentering/02_move_to_loopedge.py ./Libs/
cp -Rf ../zoo45xu/Libs/db_report_time_detail.py ./Libs/
cp -Rf ../zoo45xu/Libs/Raddose.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZooPandas_ForOldDB.py ./Libs/
cp -Rf ../zoo45xu/Libs/ESA.py ./Libs/
cp -Rf ../zoo45xu/Libs/Singleton.py ./Libs/
cp -Rf ../zoo45xu/Libs/db_dump.py ./Libs/
cp -Rf ../zoo45xu/Libs/PuckExchanger.py ./Libs/
cp -Rf ../zoo45xu/Libs/TCS.py ./Libs/
cp -Rf ../zoo45xu/Libs/BeamsizeConfig.py ./Libs/
cp -Rf ../zoo45xu/Libs/Device.py ./Libs/
cp -Rf ../zoo45xu/Libs/Light.py ./Libs/
cp -Rf ../zoo45xu/Libs/test.py ./Libs/
cp -Rf ../zoo45xu/Libs/Beamsize.py ./Libs/
cp -Rf ../zoo45xu/Libs/LoopCrystals.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_db_raster_time.py ./Libs/
cp -Rf ../zoo45xu/Libs/StopWatch.py ./Libs/
cp -Rf ../zoo45xu/Libs/CoaxPint.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_db_and_report.py ./Libs/
cp -Rf ../zoo45xu/Libs/AnaHeatmap.py ./Libs/
cp -Rf ../zoo45xu/Libs/test_analyze_heatmap.py ./Libs/
cp -Rf ../zoo45xu/Libs/CryImageProc_v2.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db.py ./Libs/
cp -Rf ../zoo45xu/Libs/CCDlen.py ./Libs/
cp -Rf ../zoo45xu/Libs/DetectorCover.py ./Libs/
cp -Rf ../zoo45xu/Libs/dtheta_tune_peak.py ./Libs/
cp -Rf ../zoo45xu/Libs/Pin.py ./Libs/
cp -Rf ../zoo45xu/Libs/myfont.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_db.py ./Libs/
cp -Rf ../zoo45xu/Libs/Mirror.py ./Libs/
cp -Rf ../zoo45xu/Libs/SummaryDat.py ./Libs/
cp -Rf ../zoo45xu/Libs/determine_att_thick.py ./Libs/
cp -Rf ../zoo45xu/Libs/Zoom.py ./Libs/
cp -Rf ../zoo45xu/Libs/AnalyzePeak.py ./Libs/
cp -Rf ../zoo45xu/Libs/M1.py ./Libs/
cp -Rf ../zoo45xu/Libs/AnaPictureMap.py ./Libs/
cp -Rf ../zoo45xu/Libs/ESA/test.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db_puckID.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_db_for_debug.py ./Libs/
cp -Rf ../zoo45xu/Libs/m1_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/BS.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZOOreporter.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZooPandas.py ./Libs/
cp -Rf ../zoo45xu/Libs/Flux.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZooPandas_ForOldDB_2.py ./Libs/
cp -Rf ../zoo45xu/Libs/Mono.py ./Libs/
cp -Rf ../zoo45xu/Libs/Gonio.py ./Libs/
cp -Rf ../zoo45xu/Libs/DirectoryProc.py ./Libs/
cp -Rf ../zoo45xu/Libs/MyDate.py ./Libs/
cp -Rf ../zoo45xu/Libs/LogString.py ./Libs/
cp -Rf ../zoo45xu/Libs/Motor.py ./Libs/
cp -Rf ../zoo45xu/Libs/DSS.py ./Libs/
cp -Rf ../zoo45xu/Libs/Crystal.py ./Libs/
cp -Rf ../zoo45xu/Libs/tcs_only_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/CryImageProc_41.py ./Libs/
cp -Rf ../zoo45xu/Libs/Att.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_attraster_beamsize.py ./Libs/
cp -Rf ../zoo45xu/Libs/UserESA.py ./Libs/
cp -Rf ../zoo45xu/Libs/db_briefhtml.py ./Libs/
cp -Rf ../zoo45xu/Libs/mu_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/ZOOhtmlMaker.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_db_warmtime.py ./Libs/
cp -Rf ../zoo45xu/Libs/CrystalSpot.py ./Libs/
cp -Rf ../zoo45xu/Libs/mirror_pin_bm.py ./Libs/
cp -Rf ../zoo45xu/Libs/Toilet.py ./Libs/
cp -Rf ../zoo45xu/Libs/ScanAxis.py ./Libs/
cp -Rf ../zoo45xu/Libs/MyException.py ./Libs/
cp -Rf ../zoo45xu/Libs/UserESA_till_202103.py ./Libs/
cp -Rf ../zoo45xu/Libs/read_flux.py ./Libs/
cp -Rf ../zoo45xu/Libs/Date.py ./Libs/
cp -Rf ../zoo45xu/Libs/Capture.py ./Libs/
cp -Rf ../zoo45xu/Libs/CountRate.py ./Libs/
cp -Rf ../zoo45xu/Libs/ScheduleBSS.py ./Libs/
cp -Rf ../zoo45xu/Libs/IDparam.py ./Libs/
cp -Rf ../zoo45xu/Libs/mod_isDone.py ./Libs/
cp -Rf ../zoo45xu/Libs/Received.py ./Libs/
cp -Rf ../zoo45xu/Libs/MirrorTuneUnit.py ./Libs/
cp -Rf ../zoo45xu/Libs/Cryo.py ./Libs/
cp -Rf ../zoo45xu/Libs/MBS.py ./Libs/
cp -Rf ../zoo45xu/Libs/GonioVec.py ./Libs/
cp -Rf ../zoo45xu/Libs/Stage.py ./Libs/
cp -Rf ../zoo45xu/Libs/att_scan.py ./Libs/
cp -Rf ../zoo45xu/Libs/CryImageProc.py ./Libs/
cp -Rf ../zoo45xu/Libs/CoaxImage.py ./Libs/
cp -Rf ../zoo45xu/Libs/scan_pixresol_INOCC.py ./Libs/
cp -Rf ../zoo45xu/06_html.py ./
cp -Rf ../zoo45xu/multi_helical.py ./
cp -Rf ../zoo45xu/tttt.py ./
cp -Rf ../zoo45xu/contour14.py ./
cp -Rf ../zoo45xu/27_set_wavelength.py ./
cp -Rf ../zoo45xu/read_db.py ./
cp -Rf ../zoo45xu/shape_recognition.py ./
cp -Rf ../zoo45xu/13_facing_test.py ./
cp -Rf ../zoo45xu/captureCam2.py ./
cp -Rf ../zoo45xu/LargePlateMatchingBC.py ./
cp -Rf ../zoo45xu/sekiguchi3.py ./
cp -Rf ../zoo45xu/HEBI_v2.py ./
cp -Rf ../zoo45xu/lys_helica_test.py ./
cp -Rf ../zoo45xu/Zoo_v2.py ./
cp -Rf ../zoo45xu/only_job.py ./
cp -Rf ../zoo45xu/t.py ./
cp -Rf ../zoo45xu/gmail_zoo_report_ver2.1.py ./
cp -Rf ../zoo45xu/sort_test.py ./
cp -Rf ../zoo45xu/plot.py ./
cp -Rf ../zoo45xu/017_gonio_capture_length_vert.py ./
cp -Rf ../zoo45xu/git_status.py ./
cp -Rf ../zoo45xu/recoverPhiLarge.py ./
cp -Rf ../zoo45xu/merge_check_all.py ./
cp -Rf ../zoo45xu/MultiCrystal_v2.py ./
cp -Rf ../zoo45xu/gmail_zoo_report_ver2.0.0.py ./
cp -Rf ../zoo45xu/make_html_from_zoodb.py ./
cp -Rf ../zoo45xu/toyoda.py ./
cp -Rf ../zoo45xu/merge_check.py ./
cp -Rf ../zoo45xu/testMount.py ./
cp -Rf ../zoo45xu/05_analyze_long_capture.py ./
cp -Rf ../zoo45xu/automerge.py ./
cp -Rf ../zoo45xu/zoo_unko.py ./
cp -Rf ../zoo45xu/21_get_beamsize.py ./
cp -Rf ../zoo45xu/check_centering.py ./
cp -Rf ../zoo45xu/start_ds_sch.py ./
cp -Rf ../zoo45xu/09_consider_exptime.py ./
cp -Rf ../zoo45xu/match_puck_and_csv.py ./
cp -Rf ../zoo45xu/db2.py ./
cp -Rf ../zoo45xu/back_cam_server.py ./
cp -Rf ../zoo45xu/evacuate_around_sample.py ./
cp -Rf ../zoo45xu/getBack.py ./
cp -Rf ../zoo45xu/check_untracked_python_codes.py ./
cp -Rf ../zoo45xu/check_flux_from_config.py ./
cp -Rf ../zoo45xu/016_gonio_capture_length_hori.py ./
cp -Rf ../zoo45xu/e.py ./
cp -Rf ../zoo45xu/test3.py ./
cp -Rf ../zoo45xu/cam2_cap.py ./
cp -Rf ../zoo45xu/lets_goto_zoo_pref_raster_step.py ./
cp -Rf ../zoo45xu/00_capture_back_series.py ./
cp -Rf ../zoo45xu/prepLarge.py ./
cp -Rf ../zoo45xu/Okkotonushi.py ./
cp -Rf ../zoo45xu/consider_exptime.py ./
cp -Rf ../zoo45xu/lets_goto_zoo_PE.py ./
cp -Rf ../zoo45xu/camera2.py ./
cp -Rf ../zoo45xu/move_to_otehon.py ./
cp -Rf ../zoo45xu/finish_bm.py ./
cp -Rf ../zoo45xu/captureLargeHolderRotCam2.py ./
cp -Rf ../zoo45xu/30_capture_time.py ./
cp -Rf ../zoo45xu/23_tune_stage.py ./
cp -Rf ../zoo45xu/clear_warning_space.py ./
cp -Rf ../zoo45xu/zoo_collect.py ./
cp -Rf ../zoo45xu/large_cameras_server.py ./
cp -Rf ../zoo45xu/mulheli.py ./
cp -Rf ../zoo45xu/screen_report.py ./
cp -Rf ../zoo45xu/check_code_diff.py ./
cp -Rf ../zoo45xu/17_get_contour.py ./
cp -Rf ../zoo45xu/html2.py ./
cp -Rf ../zoo45xu/d.py ./
cp -Rf ../zoo45xu/MultiCrystal.py ./
cp -Rf ../zoo45xu/demo.py ./
cp -Rf ../zoo45xu/19_list_available_beam.py ./
cp -Rf ../zoo45xu/db.py ./
cp -Rf ../zoo45xu/large_camera_client.py ./
cp -Rf ../zoo45xu/measure_flux.py ./
cp -Rf ../zoo45xu/11_measure_flux.py ./
cp -Rf ../zoo45xu/calc_att.py ./
cp -Rf ../zoo45xu/okkotonushi.py ./
cp -Rf ../zoo45xu/14_face_fitting.py ./
cp -Rf ../zoo45xu/capture_time.py ./
cp -Rf ../zoo45xu/ShikaDB.py ./
cp -Rf ../zoo45xu/prep_esa.py ./
cp -Rf ../zoo45xu/b.py ./
cp -Rf ../zoo45xu/HEBI.py ./
cp -Rf ../zoo45xu/xiangyu.py ./
cp -Rf ../zoo45xu/Hebi.py ./
cp -Rf ../zoo45xu/exception_test.py ./
cp -Rf ../zoo45xu/ci.py ./
cp -Rf ../zoo45xu/lets_goto_zoo_timelimit.py ./
cp -Rf ../zoo45xu/AV_helical.py ./
cp -Rf ../zoo45xu/gen_raster_test.py ./
cp -Rf ../zoo45xu/ConditionHeli.py ./
cp -Rf ../zoo45xu/28_set_skip_db.py ./
cp -Rf ../zoo45xu/mulheli_dose.py ./
cp -Rf ../zoo45xu/get_puck_info.py ./
cp -Rf ../zoo45xu/a.py ./
cp -Rf ../zoo45xu/dose_calculator.py ./
cp -Rf ../zoo45xu/31_single_irradiation.py ./
cp -Rf ../zoo45xu/KUMA_v2.py ./
cp -Rf ../zoo45xu/captureLargeHolderTransCam2.py ./
cp -Rf ../zoo45xu/merge_check_old.py ./
cp -Rf ../zoo45xu/collectOnly.py ./
cp -Rf ../zoo45xu/Inocc2.py ./
cp -Rf ../zoo45xu/22_measure_flux.py ./
cp -Rf ../zoo45xu/scanMade1.py ./
cp -Rf ../zoo45xu/unmount.py ./
cp -Rf ../zoo45xu/SearchEdge.py ./
cp -Rf ../zoo45xu/lets_goto_zoo.py ./
cp -Rf ../zoo45xu/02_tune_bin_thresh.py ./
cp -Rf ../zoo45xu/RasterSchedule.py ./
