#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Tue Jun 23 15:26:45 2020
#

import wx
import sys, os, wx.html
from wx.html import HtmlWindow

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, None, -1, "KAMO View", size=(1000, 600))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.txtworkdir = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "Browse")
        self.btn_back = wx.Button(self.panel_1, wx.ID_ANY, "Back")
        self.btn_home = wx.Button(self.panel_1, wx.ID_ANY, "Home")
        self.btn_forward = wx.Button(self.panel_1, wx.ID_ANY, "Forward")
        self.htmlwin = HtmlWindow(self.panel_1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.BrowseWorkDir, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.HtmlBack, self.btn_back)
        self.Bind(wx.EVT_BUTTON, self.HtmlHome, self.btn_home)
        self.Bind(wx.EVT_BUTTON, self.HtmlForward, self.btn_forward)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Main.__set_properties
        self.SetTitle("frame")
        self.htmlwin.SetMinSize((1000, 600))
        self.txtworkdir.SetValue(os.environ["HOME"])
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Main.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "_kamoproc directory : ")
        sizer_7.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.txtworkdir, 1, wx.EXPAND, 0)
        sizer_7.Add(self.button_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)
        sizer_3.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_4.Add(self.btn_back, 0, 0, 0)
        sizer_4.Add(self.btn_home, 0, 0, 0)
        sizer_4.Add(self.btn_forward, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)
        sizer_6.Add(self.htmlwin, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def BrowseWorkDir(self, event):
        browsedir = self.txtworkdir.GetValue()
        ddlg = wx.DirDialog(None, message="Choose a _kamoproc directory", defaultPath=browsedir)
        if ddlg.ShowModal() == wx.ID_OK:
            dname = ddlg.GetPath()
            if "_kamoproc" in dname:
                dname = dname.split("_kamoproc")[0] + "_kamoproc"
                self.txtworkdir.SetValue(dname)
                if os.path.exists(dname + "/report.html"):
                    self.htmlwin.LoadPage(dname + "/report.html")
        ddlg.Destroy()

    def HtmlBack(self, event):  # wxGlade: Main.<event_handler>
        self.htmlwin.HistoryBack()

    def HtmlHome(self, event):  # wxGlade: Main.<event_handler>
        workdir = self.txtworkdir.GetValue()
        if "_kamoproc" in workdir:
            self.htmlwin.LoadPage(workdir + "/report.html")
        else:
            self.htmlwin.LoadPage("http://bioxtal.spring8.or.jp/")
        return

    def HtmlForward(self, event):  # wxGlade: Main.<event_handler>
        self.htmlwin.HistoryForward()

class Run():
    def __init__(self):
        app = wx.PySimpleApp()
        main = Main()
        main.Show()
        app.MainLoop()

# end of class Main

